# Generated by Django 4.2.6 on 2023-11-03 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Amigos',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mi_blog.persona')),
                ('nivel_amistad', models.PositiveIntegerField()),
            ],
            bases=('mi_blog.persona',),
        ),
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mi_blog.persona')),
                ('parentesco', models.CharField(max_length=50)),
            ],
            bases=('mi_blog.persona',),
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=100)),
                ('duracion', models.IntegerField()),
                ('fecha_viaje', models.DateField()),
                ('viajeros', models.ManyToManyField(to='mi_blog.persona')),
            ],
        ),
    ]
